---
- name: Add sudoers custom configuration.
  ansible.builtin.copy:
    content: "{{ sudoers_custom_content }}"
    dest: "{{ sudoers_custom_file }}"
    mode: 0440
    validate: 'visudo -csf %s'
  become: true
