---
- name: Add sudoers custom configuration.
  ansible.builtin.copy:
    content: "{{ sudoers_custom_content }}"
    dest: /private/etc/sudoers.d/custom
    mode: 0440
    validate: 'visudo -csf %s'
  become: true
